CSS-canvas-medical exercise - Ashley Ho
ashleylho/c0822-code-solutions pull request #21
Opened 2022-08-29 02:24 UTC by ashleylho

https://user-images.githubusercontent.com/60860374/187110643-0de26a21-4029-4e86-a840-f567aeb94b03.mov

![Screen Shot 2022-08-28 at 7 23 15 PM](https://user-images.githubusercontent.com/60860374/187110651-be1f8cbf-8666-414e-8c4f-0c58bff251de.png)
![Screen Shot 2022-08-28 at 7 23 30 PM](https://user-images.githubusercontent.com/60860374/187110653-58314080-4367-4d74-93b6-21f989fe22e4.png)

2022-08-29 16:26 UTC, codingcodymiller requested changes
Hey Ashley! The logos for Canvas are images, not text, they were provided in your starter files for the project. Additionally, the "Contact Us" button in the header is too tall as compared to the example, please revise and submit a new screenshot with your revision.

2022-08-30 03:45 UTC, ashleylho commented
![Screen Shot 2022-08-29 at 8 44 54 PM](https://user-images.githubusercontent.com/60860374/187344599-33aaa03a-dc94-4cf5-87fb-4a187d0febc3.png)
![Screen Shot 2022-08-29 at 8 45 09 PM](https://user-images.githubusercontent.com/60860374/187344608-18e01f8e-788f-4df2-9d89-519ee7276c6b.png)

2022-08-30 21:55 UTC, codingcodymiller requested changes

2022-08-30 21:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
When naming `column` classes, the `column` portion should come before the measurement, so it is clear at a glance that it is meant to represent a `column` layout class. Also, `two` does not make it clear what the size for this class is. I would rename this to `column-half`. Please make sure to do the same on any other `column-` classes you have in your layout.

Additionally, you should not create variants of `column-` classes based on where it is being applied. You should just use one `column-half` class for all situations requiring a 50% width column.

Lastly, `column-` classes should only include a `flex-basis` or `width` property, and nothing else. You should move the `margin` on this class to another class that you can add to the element in addition to the `column-` class.

2022-08-31 16:22 UTC, codingcodymiller approved these changes
Great work!!

2022-08-31 19:21 UTC, merged