Javascript-light-bulb exercise - Ashley Ho
ashleylho/c0822-code-solutions pull request #44
Opened 2022-09-06 23:44 UTC by ashleylho

https://user-images.githubusercontent.com/60860374/188758876-05b35c5f-548d-4dac-9c15-4a43062247d8.mov

2022-09-07 16:09 UTC, codingcodymiller requested changes

2022-09-07 16:09 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if ($body.className === 'lightbulb') {
By doing this, your logic is dependent on the current state of the DOM, which is not ideal. Instead, I would create a variable to keep track of if the light is currently on or not, and use that variable's value to determine what action to take when the light is clicked.

2022-09-07 20:17 UTC, ashleylho commented
![Screen Shot 2022-09-07 at 1 17 35 PM](https://user-images.githubusercontent.com/60860374/188969249-4a4ffc89-bcfd-481c-9804-8785cdf0a5ce.png)

2022-09-07 20:36 UTC, codingcodymiller requested changes

2022-09-07 20:36 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (currentStatus === 'lightbulb') {
This is the same problem but now in a new variable 🤩

2022-09-07 20:36 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (currentStatus === 'lightbulb') {
You should make a variable that has a boolean value to keep track of whether the light is on or not and use that variable to determine what action to take each time the lightbulb is clicked.

2022-09-08 03:05 UTC, ashleylho commented on javascript-light-bulb/main.js
> +  if (currentStatus === 'lightbulb') {
> This is the same problem but now in a new variable 🤩

My bad.... 😅

2022-09-08 03:06 UTC, ashleylho commented
<img width="701" alt="Screen Shot 2022-09-07 at 8 06 15 PM" src="https://user-images.githubusercontent.com/60860374/189025000-fc77dceb-0af0-44d3-95df-4dc61a34f118.png">

2022-09-08 15:41 UTC, codingcodymiller approved these changes

2022-09-08 15:58 UTC, merged